/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.lab1;

import javax.swing.JOptionPane;

/**
 *
 * @author acer
 */
public class FrBai2 extends javax.swing.JFrame {

    /**
     * Creates new form FrBai2
     */
    public FrBai2() {
        initComponents();
    }

    public boolean checkNull(){
        if(txt1.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Chưa nhập giá trị");
            txt1.requestFocus();
            return false;
        } else if(txt2.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Chưa nhập giá trị");
            txt2.requestFocus();
            return false;
        }else
            return true;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BntPlus = new javax.swing.JButton();
        txt1 = new javax.swing.JTextField();
        txt2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        bntMinus = new javax.swing.JButton();
        bntMutiple = new javax.swing.JButton();
        bntDivide = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtResult = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("First Number:");

        BntPlus.setText("+");
        BntPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BntPlusActionPerformed(evt);
            }
        });

        jLabel3.setText("Second Number:");

        bntMinus.setText("-");
        bntMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntMinusActionPerformed(evt);
            }
        });

        bntMutiple.setText("*");
        bntMutiple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntMutipleActionPerformed(evt);
            }
        });

        bntDivide.setText("/");
        bntDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntDivideActionPerformed(evt);
            }
        });

        jLabel4.setText("Result:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtResult, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(BntPlus)
                        .addGap(18, 18, 18)
                        .addComponent(bntMinus)
                        .addGap(18, 18, 18)
                        .addComponent(bntMutiple)
                        .addGap(18, 18, 18)
                        .addComponent(bntDivide)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BntPlus)
                    .addComponent(bntMinus)
                    .addComponent(bntMutiple)
                    .addComponent(bntDivide))
                .addGap(51, 51, 51))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BntPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BntPlusActionPerformed
        // TODO add your handling code here:
        float so1,so2;
        double rs;
        if(checkNull()){
            so1 = Float.parseFloat(txt1.getText());
            so2 = Float.parseFloat(txt2.getText());
            rs = so1 + so2;
            txtResult.setText(rs+"");
        }
    }//GEN-LAST:event_BntPlusActionPerformed

    private void bntMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntMinusActionPerformed
        // TODO add your handling code here:
        float so1,so2;
        double rs;
        if(checkNull()){
            so1 = Float.parseFloat(txt1.getText());
            so2 = Float.parseFloat(txt2.getText());
            rs = so1 - so2;
            txtResult.setText(rs+"");
        }
    }//GEN-LAST:event_bntMinusActionPerformed

    private void bntMutipleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntMutipleActionPerformed
        // TODO add your handling code here:
        float so1,so2;
        double rs;
        if(checkNull()){
            so1 = Float.parseFloat(txt1.getText());
            so2 = Float.parseFloat(txt2.getText());
            rs = so1 * so2;
            txtResult.setText(rs+"");
        }
    }//GEN-LAST:event_bntMutipleActionPerformed

    private void bntDivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntDivideActionPerformed
        // TODO add your handling code here:
        float so1,so2;
        double rs;
        if(Float.parseFloat(txt2.getText())==0){
            JOptionPane.showMessageDialog(this, "Không thể chia với 0");
            txt2.requestFocus();
        }else if(checkNull()){
            so1 = Float.parseFloat(txt1.getText());
            so2 = Float.parseFloat(txt2.getText());
            rs = so1 / so2;
            String lamtron = String.format("%.2f", rs);
            txtResult.setText(lamtron+"");
        }
    }//GEN-LAST:event_bntDivideActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrBai2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrBai2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrBai2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrBai2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrBai2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BntPlus;
    private javax.swing.JButton bntDivide;
    private javax.swing.JButton bntMinus;
    private javax.swing.JButton bntMutiple;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt2;
    private javax.swing.JTextField txtResult;
    // End of variables declaration//GEN-END:variables
}
